<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adc010a0b68656c6c6f2e70726f746f12046772706322200a0c48656c6c" .
            "6f5265717565737412100a086772656574696e67180120012809221e0a0d" .
            "48656c6c6f526573706f6e7365120d0a057265706c791801200128093243" .
            "0a0c48656c6c6f5365727669636512330a0853617948656c6c6f12122e67" .
            "7270632e48656c6c6f526571756573741a132e677270632e48656c6c6f52" .
            "6573706f6e736532380a045465737412300a05536179787812122e677270" .
            "632e48656c6c6f526571756573741a132e677270632e48656c6c6f526573" .
            "706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

